-- +goose Up
CREATE TABLE IF NOT EXISTS users (
	id VARCHAR(36) NOT NULL,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS channels (
	id VARCHAR(36) NOT NULL,
	name VARCHAR(255) NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	PRIMARY KEY (id)
);
